name: Test
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_call: {}

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.12"]
    steps:
      - name: Checkout Repository And Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Install Pydivsufsort And Other Dependencies
        run: |
          python -m pip install pytest flake8 coverage
          # -e installs locally, else coverage fails                  
          python -m pip install -v -e .
        shell: bash
      - name: Display NumPy Version
        run: python -c "import numpy; print(numpy.__version__)"
        shell: bash
      - name: Run Flake8
        run: flake8 .
        shell: bash
      - name: Run Unit Tests
        run: |
          coverage run -m pytest tests
          coverage xml
        shell: bash
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
